In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a,b)
print(c)

32


In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [4]:
from dezero import Variable
import dezero.functions as F

In [9]:
x = Variable(np.random.randn(2,3))
W = Variable(np.random.randn(3,4))
y = F.matmul(x,W)
print(y)
y.backward()
print(y)
print(x.grad.shape)
print(W.grad.shape)

variable([[-0.7285632   0.33606472 -0.06630558  2.00542021]
          [ 1.35445866  2.61739977  0.56704148 -0.05383719]])
variable([[-0.7285632   0.33606472 -0.06630558  2.00542021]
          [ 1.35445866  2.61739977  0.56704148 -0.05383719]])
(2, 3)
(3, 4)
