In [1]:
import numpy as np
from dezero import Variable
import dezero.functions as F

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y = np.reshape(x,(6,))
print(y)

[1 2 3 4 5 6]


In [3]:
x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.transpose(x)
print(y)
y.backward(retain_grad=True)
print(x.grad)

variable([[1 4]
          [2 5]
          [3 6]])
variable([[1 1 1]
          [1 1 1]])


In [4]:
x = Variable(np.random.randn(2,3))
y = x.transpose()
print(y)
y = x.T
y

variable([[-0.45990388 -2.69720572]
          [-1.38188713 -0.82239846]
          [ 0.04225457  0.73864088]])


variable([[-0.45990388 -2.69720572]
          [-1.38188713 -0.82239846]
          [ 0.04225457  0.73864088]])

In [6]:
A,B,C,D = 1,2,3,4
x = np.random.rand(A,B,C,D)
print(x)
y = x.transpose(3,2,1,0)
y

[[[[0.93668804 0.03172204 0.68444669 0.23682273]
   [0.48987516 0.51662335 0.63273419 0.37261267]
   [0.87242291 0.20851944 0.51156472 0.40463767]]

  [[0.07409085 0.27219067 0.16065011 0.05439974]
   [0.84407033 0.17392848 0.40508377 0.58880657]
   [0.79263545 0.34784882 0.10022441 0.72872512]]]]


array([[[[0.93668804],
         [0.07409085]],

        [[0.48987516],
         [0.84407033]],

        [[0.87242291],
         [0.79263545]]],


       [[[0.03172204],
         [0.27219067]],

        [[0.51662335],
         [0.17392848]],

        [[0.20851944],
         [0.34784882]]],


       [[[0.68444669],
         [0.16065011]],

        [[0.63273419],
         [0.40508377]],

        [[0.51156472],
         [0.10022441]]],


       [[[0.23682273],
         [0.05439974]],

        [[0.37261267],
         [0.58880657]],

        [[0.40463767],
         [0.72872512]]]])